/**
 * API client for the VA GMWB Calculator backend.
 *
 * In development, Vite proxies /api → http://localhost:8000 (see vite.config.js).
 * In production, set VITE_API_URL to the Lambda Function URL.
 */

import axios from 'axios';

const BASE_URL = import.meta.env.VITE_API_URL
  ? import.meta.env.VITE_API_URL
  : '/api';

const client = axios.create({
  baseURL: BASE_URL,
  timeout: 60_000,
  headers: { 'Content-Type': 'application/json' },
});

/**
 * Run the Monte Carlo simulation.
 * @param {Object} params - SimulateRequest fields (see backend/main.py)
 * @returns {Promise<Object>} SimulationResult
 */
export async function simulate(params) {
  const { data } = await client.post('/simulate', params);
  return data;
}

/**
 * Run a historical-replay backtest against actual S&P 500 returns.
 * @param {Object} params - SimulateRequest fields
 * @param {string} startMonth - YYYY-MM (e.g. '2007-01')
 * @returns {Promise<Object>} HistoricalResult — single AV path, PV figures, depletion info
 */
export async function backtest(params, startMonth) {
  const { data } = await client.post('/backtest', { ...params, start_month: startMonth });
  return data;
}

/**
 * Run sensitivity analysis (tornado chart data).
 * @param {Object} base - SimulateRequest fields
 * @param {number} shiftPct - relative shift, e.g. 0.10 for ±10%
 * @param {string[]|null} fields - which parameter fields to stress-test; null = all
 * @returns {Promise<Object>} { base_net_cost, sensitivities[] }
 */
export async function sensitivity(base, shiftPct = 0.10, fields = null) {
  const body = { base, shift_pct: shiftPct };
  if (fields !== null) body.fields = fields;
  const { data } = await client.post('/sensitivity', body);
  return data;
}

/**
 * Find the optimal GMWB election age by sweeping across possible start ages.
 * @param {Object} params - SimulateRequest fields
 * @returns {Promise<Object>} { sweep, optimal_age, optimal_pv_gmwb, optimal_annual_gaw, current_election_age, current_pv_gmwb }
 */
export async function optimalElectionAge(params) {
  const { data } = await client.post('/optimal_election_age', { base: params });
  return data;
}

/**
 * Fire-and-forget: persist a simulation session for research/analytics.
 * Silently swallows errors so a record failure never breaks the UI.
 * @param {Object} payload - { email, role, mode, params, results, extra }
 */
export async function recordSession(payload) {
  try {
    await client.post('/record', payload);
  } catch (_) {
    // non-critical — never surface to user
  }
}

/**
 * Send a 6-digit OTP to the supplied email address.
 * In dev (no SMTP/SES configured) the code is printed to the server console.
 * @param {string} email
 * @returns {Promise<{ sent: boolean }>}
 */
export async function sendOtp(email) {
  const { data } = await client.post('/auth/send-otp', { email });
  return data;
}

/**
 * Verify the 6-digit OTP.
 * @param {string} email
 * @param {string} code  - exactly 6 digits
 * @returns {Promise<{ verified: boolean, email: string }>}
 */
export async function verifyOtp(email, code) {
  const { data } = await client.post('/auth/verify-otp', { email, code });
  return data;
}

/**
 * Ratings-publication endpoints (listRatings / getRating / getMethodology):
 *
 * These are read-only JSON pulls that are also pre-rendered into static HTML
 * via the SSG pipeline (frontend/scripts/prerender.mjs). To make the SSG
 * crawler self-contained (no uvicorn required) AND keep production resilient
 * when the FastAPI service is cold-starting, we serve them from a build-time
 * snapshot committed to `/ratings-data/*.json` (generated by
 * scripts/generate-ratings-snapshot.mjs into frontend/public/ratings-data/).
 *
 * The snapshot path uses `/ratings-data/` rather than `/api-snapshot/` so the
 * dev server's `/api` proxy (which is prefix-based in Vite) doesn't intercept
 * the request and forward it to FastAPI.
 *
 * The snapshot path is tried first; if it 404s (e.g. dev environment that
 * never ran the generator) we fall back to the live FastAPI /api routes.
 *
 * Calculator endpoints (/simulate, /sensitivity, …) still go to /api as
 * before — they're dynamic and have no equivalent snapshot.
 */
const SNAPSHOT_BASE = '/ratings-data';

async function getJsonSnapshotFirst(snapshotPath, apiPath) {
  try {
    const res = await fetch(SNAPSHOT_BASE + snapshotPath, { headers: { Accept: 'application/json' } });
    if (res.ok) {
      const text = await res.text();
      // Vite's dev server returns index.html for unknown paths inside the public
      // dir; guard against that masquerading as JSON.
      if (text && text.trimStart().startsWith('{')) return JSON.parse(text);
    }
  } catch (_) {
    // network/parse — fall through to API
  }
  const { data } = await client.get(apiPath);
  return data;
}

/**
 * List every published rating (composite-sorted desc).
 * @returns {Promise<{ count, methodology_version, methodology_effective_date, items }>}
 */
export async function listRatings() {
  return getJsonSnapshotFirst('/ratings.json', '/ratings');
}

/**
 * Load one rating + its product spec by slug.
 * @param {string} slug
 * @returns {Promise<{ rating, product }>}
 */
export async function getRating(slug) {
  return getJsonSnapshotFirst(`/ratings/${slug}.json`, `/ratings/${slug}`);
}

/**
 * Load the methodology JSON.
 * @returns {Promise<Object>} methodology doc
 */
export async function getMethodology() {
  return getJsonSnapshotFirst('/methodology.json', '/methodology');
}

/**
 * Replay one published product against one historical regime, normalized to a
 * starting AV of $100. Deterministic (no Monte Carlo), and NOT a composite
 * rating input — strictly a user-facing what-if scenario.
 *
 * @param {string} slug        product slug, e.g. "equitable_scs_income"
 * @param {string} regimeKey   methodology regime key, e.g. "post_gfc_bull_2010_2021"
 * @returns {Promise<Object>}  { av_path, terminal_av, terminal_av_multiple,
 *                               max_drawdown_pct, max_drawdown_month,
 *                               fees_paid_total, fee_drag_annualized_pct, … }
 */
export async function getRegimeBacktest(slug, regimeKey) {
  const { data } = await client.get(`/ratings/${slug}/backtest/${regimeKey}`);
  return data;
}

/**
 * Cap-rate freshness summary for a product. Returns per-segment last-verified
 * date + status color (green ≤30 days, yellow ≤90, red older / unverified).
 */
export async function getRatingFreshness(slug) {
  const { data } = await client.get(`/ratings/${slug}/freshness`);
  return data;
}
